name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: npm run build
      
    - name: Deploy to gh-pages
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Create or switch to gh-pages branch
        if git show-ref --verify --quiet refs/heads/gh-pages; then
          git checkout gh-pages
          git pull origin gh-pages
        else
          git checkout --orphan gh-pages
        fi
        
        # Remove all files first
        git rm -rf . || true
        
        # Copy built files from dist directory
        cp -r dist/* . || true
        
        # Copy additional directories that might not be in dist
        if [ -d "pages" ]; then cp -r pages .; fi
        if [ -d "assets" ]; then cp -r assets .; fi
        if [ -d "config" ]; then cp -r config .; fi
        if [ -d "includes" ]; then cp -r includes .; fi
        if [ -d "admin" ]; then cp -r admin .; fi
        
        # Copy root files
        cp *.html . 2>/dev/null || true
        cp *.php . 2>/dev/null || true
        cp *.md . 2>/dev/null || true
        cp *.json . 2>/dev/null || true
        
        # Create .nojekyll file
        echo "" > .nojekyll
        
        # Add and commit
        git add .
        git commit -m "Deploy: $(date)" || exit 0
        git push origin gh-pages --force
        
        # Switch back to main
        git checkout main
